# Generated by Django 5.2.6 on 2026-03-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_esperada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Recibida'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('productos_que_surte', models.TextField(blank=True, null=True)),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_venta', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_mayorista', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_stock', models.IntegerField(default=5)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='gestion.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('factor', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
            options={
                'db_table': 'presentaciones_producto',
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
            options={
                'db_table': 'merma',
            },
        ),
        migrations.CreateModel(
            name='DevolucionProveedor',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('id_orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.CASCADE, to='gestion.ordencompra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
            options={
                'db_table': 'devoluciones_proveedores',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id_detalle_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.CASCADE, to='gestion.ordencompra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
            options={
                'db_table': 'detalle_orden_compra',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('id_presentacion', models.ForeignKey(db_column='id_presentacion', on_delete=django.db.models.deletion.CASCADE, to='gestion.presentacionproducto')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='gestion.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
