# Generated by Django 5.2.6 on 2026-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_producto_barcode_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sku_prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ultimo_sku_numero',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
