# Generated by Django 5.2.6 on 2026-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_fix_duplicate_skus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='sku_prefix',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
